load("@rules_go//go:def.bzl", "go_binary", "go_library")

go_library(
    name = "nexttag_lib",
    srcs = ["main.go"],
    importpath = "github.com/stefanpenner/devlayer/tools/nexttag",
    visibility = ["//visibility:private"],
    deps = ["//internal/nexttag"],
)

go_binary(
    name = "nexttag",
    embed = [":nexttag_lib"],
    visibility = ["//visibility:public"],
)
